#!/bin/bash

commit_message_file="$1"
RED='\033[0;31m'
NC='\033[0m'
# Check if the commit message file exists and is not empty
if [ -s "$commit_message_file" ]; then
  echo "Commit message file: $commit_message_file"

  # Check if the commit message follows the conventional format
  if ! grep -E '^(feat|fix|docs|style|refactor|test|chore)(\([A-Za-z0-9_.-]+\))?AF-[0-9]+: .+' "$commit_message_file"; then
    echo 
    echo "**************************************************************************"
    echo "Invalid commit message format. Please use conventional commit messages." >&2
    echo -e "${RED}Format example : feat(auth)AF-123: add inputs authentication${NC}"
    echo "**************************************************************************"
    echo
    exit 1
  fi
else
  echo "No commit message provided."
  exit 1
fi
